# Generated by Django 5.1.4 on 2024-12-26 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True, verbose_name='Nome Categoria')),
                ('descrizione', models.TextField(blank=True, null=True, verbose_name='Descrizione')),
            ],
            options={
                'verbose_name_plural': 'Categorie',
            },
        ),
        migrations.CreateModel(
            name='Spesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=255, verbose_name='Proprietario')),
                ('spesa', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Importo')),
                ('data', models.DateField(verbose_name='Data')),
                ('saldata', models.BooleanField(default=False, verbose_name='Saldato')),
                ('categorie', models.ManyToManyField(blank=True, related_name='spese', to='spesa.categoria', verbose_name='Categorie')),
            ],
            options={
                'verbose_name_plural': 'Spese',
            },
        ),
    ]
