# Generated by Django 5.1.4 on 2024-12-27 11:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spesa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spesa',
            name='data',
            field=models.DateField(default=datetime.datetime(2024, 12, 27, 11, 32, 52, 159646, tzinfo=datetime.timezone.utc), verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='spesa',
            name='owner',
            field=models.CharField(choices=[('Mattia', 'Mattia'), ('Annalisa', 'Annalisa')], max_length=255, verbose_name='Proprietario'),
        ),
    ]
